name: Deploy to Pages

on:
  push:
    branches: [main, dev]
  workflow_dispatch:
  
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "[Build] Checkout repo"
        uses: actions/checkout@v5

      - name: "[Build] Setup Deno"
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x 

      - name: "[Build] Install dependencies"
        run: deno install

      - name: "[Build] Build"
        run: deno task build

      - name: "[Deploy] Push to gh-pages"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          target-folder: ${{ github.ref_name }} 
          clean: false 
