name: Deploy to Pages

on:
  push:
    branches: [main, dev]
  workflow_dispatch:
  
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "[Pre-Deploy] Checkout repo"
        uses: actions/checkout@v5

      - name: "[Check] Setup Deno"
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x 

      - name: "[Check] Deno Check"
        run: deno check

      - name: "[Pre-Deploy] Remove unnecessary files"
        run: |
          # 刪除不想要在 GitHub Pages 看到的文件
          rm -rf .github
          rm -f .gitignore
          rm -f README.md
          rm -f deno.jsonc
          rm -f deno.lock

      - name: "[Deploy] Push to gh-pages"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          target-folder: ${{ github.ref_name }} 
          clean: false 
